name: Daily Commit Automation

on:
  schedule:
    - cron: '15 4 * * *'  # Runs daily at 4:15 AM UTC (customize as needed)
  workflow_dispatch:  # Optional: allows manual trigger too

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Daily Commit - 24f2001293@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update commit - $(date)"
          git push
